# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1f5c26b022c0180ef059f7dbd8f21ae8626922baf8014a1b9d39f18bceeed97de917adb7b3be7ba2980a6fd6bc397a84d9cd111abb34c7f218fba7f676da705
  hmac_key: M34FL2fdkSEGheoYtFdYyuwEFDtsiEG7fXLtlWRW
  token_algo: HS256

test:
  secret_key_base: a0ae63e71de79188624b265721448696f75130ac53b2902e9c1f7d4cafcb932b70e2d541eaef7af83989e1724d1d6c877631ea0a65dc658230096ef8d0144e81
  hmac_key: JoFRMXiDpyVMo+WyX5hfNtR7abX2r9LooTABqpwu
  token_algo: HS256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  hmac_key: <%= ENV["HMAC_KEY"] %>
  token_algo: HS256
